baseURL = 'https://farinha.info/'
languageCode = 'pt-br'
title = 'Farinha'

theme = 'hugo-universal-theme'
style = "default"

[params]
    disabled_logo = false
    logo_text = "Universal"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"


[menu]

# Main menu
[[menu.main]]
    name       = "Inicial"
    identifier = "menu.inicial"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "O software"
    url        = "/"
    weight     = 1
    parent     = "menu.inicial"

[[menu.main]]
    name       = "A equipe"
    url        = "/"
    weight     = 2
    parent     = "menu.inicial"