baseURL = 'https://farinha.info/'
languageCode = 'pt-br'
defaultContentLanguage = "pt-br"
title = 'Farinha'

theme = 'hugo-universal-theme'
style = "default"

[params]
    disabled_logo = false
    logo_text = "Farinha"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"

    # footer
    about_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"

    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Universal Ltd.</strong>
        <br>13/25 New Avenue
        <br>Newtown upon River
        <br>45Y 73J
        <br>England
        <br>
        <strong>Great Britain</strong>
        </p>
        """
    # end footer

[params.topbar]
    enable = true
    text = "<p>Entre em contato por contato@farinha.info</p>"

[menu]

# Main menu
[[menu.main]]
    name       = "Inicial"
    identifier = "menu.inicial"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "O software"
    url        = "/"
    weight     = 1
    parent     = "menu.inicial"

[[menu.main]]
    name       = "A equipe"
    url        = "/"
    weight     = 2
    parent     = "menu.inicial"


# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Gitlab"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Instagram"
    url = "http://facebook.com"
    pre = "<i class='fab fa-2x fa-instagram'></i>"

[[menu.topbar]]
    weight = 3
    name = "Email"
    url = "mailto:hello@universal.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"


[params.carouselHomepage]
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000


[params.features]
    enable = true
    cols = 4


[params.testimonials]
    enable = true
    title = "Depoimentos"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."


[params.clients]
    enable = true
    title = "Parceiros"
    subtitle = "Orgulhosamente colaboramos com essas instituições."
