baseURL = 'https://farinha.info/'
languageCode = 'pt-br'
title = 'Farinha'

theme = 'hugo-universal-theme'
style = "default"

[params]
    disabled_logo = false
    logo_text = "Universal"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"


[menu]

# Main menu
[[menu.main]]
    name       = "Inicial"
    identifier = "menu.inicial"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "O software"
    url        = "/"
    weight     = 1
    parent     = "menu.inicial"

[[menu.main]]
    name       = "A equipe"
    url        = "/"
    weight     = 2
    parent     = "menu.inicial"


# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Gitlab"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Instagram"
    url = "http://facebook.com"
    pre = "<i class='fab fa-2x fa-instagram'></i>"

[[menu.topbar]]
    weight = 3
    name = "Email"
    url = "mailto:hello@universal.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"