baseURL = 'https://farinha.info/'
languageCode = 'pt-br'
defaultContentLanguage = "pt-br"
title = 'Farinha'

theme = 'hugo-universal-theme'
style = "default"

[params]
    disabled_logo = false
    logo_text = "Farinha"

    logo = "img/logo_farinha.png"
    logo_small = "img/logo_farinha.png"

    # footer
    about_us = """<ul>
        <li><img src="/img/badges/badge-python.svg" alt="Python"/></li>
        <p>
        <li><img src="/img/badges/badge-django.svg" alt="Django"/></li>
        <p>
        <li><img src="/img/badges/badge-hugo.svg" alt="HUGO"/></li>
        <p>
        <li><img src="/img/badges/badge-bulma.svg" alt="BulmaCSS"/></li>
    </ul>"""
    # contact_url = "/contact"
    address = """
        <br>Salvador/BA
        <br>Brasil
        <br>
        <br>
        <a href="mailto:contato@farinha.info">contato@farinha.info</a>
        <br>
        </p>
        """
    # end footer

[params.topbar]
    enable = true
    text = "<p>Entre em contato por contato@farinha.info</p>"

#[menu]
#
## Main menu
#[[menu.main]]
#    name       = "Inicial"
#    identifier = "menu.inicial"
#    url        = "/"
#    weight     = 1
#
#[[menu.main]]
#    name       = "O software"
#    url        = "/"
#    weight     = 1
#    parent     = "menu.inicial"
#
#[[menu.main]]
#    name       = "A equipe"
#    url        = "/"
#    weight     = 2
#    parent     = "menu.inicial"


# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Github"
    url = "https://github.com/rsandrade/farinha.info"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Instagram"
    url = "#"
    pre = "<i class='fab fa-2x fa-instagram'></i>"

[[menu.topbar]]
    weight = 3
    name = "Email"
    url = "mailto:contato@farinha.info"
    pre = "<i class='fas fa-2x fa-envelope'></i>"


[params.carouselHomepage]
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000


[params.features]
    enable = true
    cols = 4


[params.testimonials]
    enable = true
    title = "Equipe"
    subtitle = ""


[params.clients]
    enable = true
    title = "Parceiros"
    subtitle = ""
