baseURL = 'https://farinha.info/'
languageCode = 'pt-br'
title = 'Farinha'

theme = 'hugo-universal-theme'
style = "default"

[params]
    disabled_logo = false
    logo_text = "Universal"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"