baseURL = 'https://farinha.info/'
languageCode = 'pt-br'
title = 'Farinha'
theme = 'hugo-universal-theme'

style = "default"

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[menu]

# Main menu
[[menu.main]]
    name       = "Inicial"
    identifier = "menu.inicial"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "O que é?"
    url        = "/"
    weight     = 1
    parent     = "menu.inicial"

[[menu.main]]
    name       = "Quem faz?"
    url        = "/"
    weight     = 2
    parent     = "menu.inicial"

[[menu.main]]
    name       = "Contato"
    identifier = "menu.contato"
    url        = "/contato"
    weight     = 2