baseURL = 'https://farinha.info/'
languageCode = 'pt-br'
title = 'Farinha'
theme = 'hugo-universal-theme'

style = "default"

[menu]


# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1