baseURL = 'https://farinha.info/'
languageCode = 'pt-br'
defaultContentLanguage = "pt-br"
title = 'Farinha'

theme = 'hugo-universal-theme'
style = "default"

[params]
    disabled_logo = false
    logo_text = "Farinha"

    logo = "img/logo_farinha.png"
    logo_small = "img/logo_farinha.png"

    # footer
    about_us = "<p>O <strong>Farinha</strong> é um software livre desenvolvido com o objetivo de facilitar a gestão de arquivos permanentes, de valor histórico.</p><p>Nossa missão é proporcionar uma <b>plataforma livre, robusta, acessível</b> para instituições que desejam preservar e compartilhar seu patrimônio documental</p><p>O projeto é mantido e desenvolvido de forma colaborativa, com o código-fonte aberto e disponível para todas as instituições interessadas.</p>"

    contact_url = "/contact"
    address = """<p>
        <br>Salvador/BA
        <br>Brasil
        <br>
        <br>
        <a href="mailto:contato@farinha.info">contato@farinha.info</a>
        <br>
        </p>
        """
    # end footer

[params.topbar]
    enable = true
    text = "<p>Entre em contato por contato@farinha.info</p>"

[menu]

# Main menu
[[menu.main]]
    name       = "Inicial"
    identifier = "menu.inicial"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "O software"
    url        = "/"
    weight     = 1
    parent     = "menu.inicial"

[[menu.main]]
    name       = "A equipe"
    url        = "/"
    weight     = 2
    parent     = "menu.inicial"


# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Github"
    url = "https://github.com/rsandrade/farinha.info"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Instagram"
    url = "#"
    pre = "<i class='fab fa-2x fa-instagram'></i>"

[[menu.topbar]]
    weight = 3
    name = "Email"
    url = "mailto:contato@farinha.info"
    pre = "<i class='fas fa-2x fa-envelope'></i>"


[params.carouselHomepage]
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000


[params.features]
    enable = true
    cols = 4


[params.testimonials]
    enable = true
    title = "Depoimentos"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."


[params.clients]
    enable = true
    title = "Parceiros"
    subtitle = "Orgulhosamente colaboramos com essas instituições."
